services:
  db:
    image: postgres:16
    container_name: sigma_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./ddl.sql:/docker-entrypoint-initdb.d/ddl.sql

  app:
    build: .
    container_name: sigma_python
    working_dir: /app
    volumes:
      - .:/app
    depends_on:
      - db
    ports:
      - "8000:8000"
    command: bash -lc "uvicorn main:app --host 0.0.0.0 --port 8000"

volumes:
  pgdata:
